added hero parts files
vikadmin88/project-CCrafters-JS pull request #14
Opened 2024-02-10 17:35 UTC by StronDator

2024-02-10 19:34 UTC, vikadmin88 requested changes

2024-02-10 19:34 UTC, vikadmin88 commented on src/css/hero.css
> +.hero {
Треба додати падінги  для відступів зверху-знизу
top 20px, bottom 10px  (половина від макетної)  кожна секція додає половину.

2024-02-10 19:34 UTC, vikadmin88 commented on src/css/hero.css
> +  margin-top: 20px;
Маржин не потрібний. Відступ на секції

2024-02-10 19:34 UTC, vikadmin88 commented on src/css/hero.css
> +    margin-top: 16px;
маржин не потрібен

2024-02-10 19:34 UTC, vikadmin88 commented on src/css/hero.css
> +@media screen and (min-width: 768px) {
додай до секції херо падінги топ 16, ботом 8

2024-02-10 19:34 UTC, vikadmin88 commented on src/css/hero.css
> +    margin-top: 20px;
маржин не потрібен

2024-02-10 19:34 UTC, vikadmin88 commented on src/css/hero.css
> +@media screen and (min-width: 1440px) {
до секції  херо додай падінги топ 16, ботом 8

2024-02-10 19:52 UTC, Musteks555 commented
В .hero-title можно не указывать width в пикселях, достаточно написать width: 100% и всё, остальное лишнее.

В .hero-title letter-spacing указываем в em'ах, то есть будет -0.02em для моб версии(для других версий другие значения).

В .hero-paragraph letter-spacing указываем в em'ах, то есть будет -0.01em для моб версии(для других версий другие значения).

В .tags для планшетной и десктопной версиях нужно сделать gap: 8px.

В .tag для планшетной и десктопной версиях нужно сделать font-size: 16px и line-height: 1.5

2024-02-11 22:15 UTC, vikadmin88 approved these changes
done

2024-02-11 22:16 UTC, merged